# Generated by Django 5.1.6 on 2025-03-04 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('home_id', models.AutoField(primary_key=True, serialize=False)),
                ('localization', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('name', models.CharField(default='Dom <django.db.models.fields.AutoField>', max_length=200)),
                ('code', models.CharField(default='9cUFdJmhjIORYq10a9t5', max_length=100)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('user_type', models.CharField(default='klient', max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Czujnik <django.db.models.fields.AutoField>', max_length=200)),
                ('created_at', models.DateField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.home')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Pomiar <django.db.models.fields.AutoField>', max_length=200)),
                ('value', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('created_at', models.DateField()),
                ('saved_at', models.DateField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.sensor')),
            ],
        ),
    ]
