# Generated by Django 5.1.6 on 2025-03-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='CMk3TVo1LrcKIBpiX5eL', max_length=100),
        ),
    ]
