# Generated by Django 5.1.6 on 2025-03-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_user_id_appuser_id_remove_appuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='ZvJmYbXuHQTjjPlcwjd6', max_length=100),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Czujnik <django.db.models.fields.AutoField>', max_length=200)),
                ('created_at', models.DateField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.home')),
            ],
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.device'),
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
