# Generated by Django 5.1.6 on 2025-03-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_home_code_device_alter_measurement_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='J0TQIrSwgFOaDpK7btjP', max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='localization',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
