# Generated by Django 5.1.6 on 2025-03-07 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_home_code_alter_home_localization'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='sTHjQKmFJZe7zTNWcPww', max_length=100),
        ),
    ]
