# Generated by Django 5.1.6 on 2025-03-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_home_owner_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='EZFdD9jLrOnOEuX7mCyR', max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
