# Generated by Django 5.1.6 on 2025-03-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_home_code_alter_home_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='localization',
        ),
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='regards',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='LJxF6SBbEeRngJ0LYW5p', max_length=100),
        ),
    ]
