# Generated by Django 5.1.6 on 2025-03-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_remove_home_localization_home_address_home_regards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='floor_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='W2XJEqFpwgB6TVOT5BPG', max_length=100),
        ),
    ]
