# Generated by Django 5.1.6 on 2025-03-09 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_home_floor_num_alter_home_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='home',
        ),
        migrations.AddField(
            model_name='home',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='1oRF4JNmUhte53MkRXCq', max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Pokój', max_length=200)),
                ('light', models.BooleanField(default=False)),
                ('warning', models.BooleanField(default=False)),
                ('position', models.JSONField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.home')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.room'),
        ),
    ]
