# Generated by Django 5.1.6 on 2025-03-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_home_code_floor_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='srii7VrWykL48Olmdra5', max_length=100),
        ),
    ]
