# Generated by Django 5.1.6 on 2025-03-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='78NOkIBxDu9hNxKkC6om', max_length=100),
        ),
    ]
