# Generated by Django 5.1.7 on 2025-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='79ky0S6enW5P8pkp11n3', max_length=100),
        ),
    ]
