# Generated by Django 5.1.7 on 2025-03-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='info',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.CharField(default='#ff2288', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='dmDjc83JQ35rtowNBkP7', max_length=100),
        ),
    ]
