# Generated by Django 5.1.7 on 2025-03-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_device_brand_alter_home_code_alter_room_color_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='f2shyJMfbXQpnweuRydX', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='color',
            field=models.CharField(blank=True, default='#42adf5', max_length=20, null=True),
        ),
    ]
