# Generated by Django 5.1.7 on 2025-03-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_alter_home_code_alter_room_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='XWAMAqyomwInqj6EEHy0', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='color',
            field=models.CharField(default='#42adf5', max_length=20),
        ),
    ]
