# Generated by Django 5.1.7 on 2025-04-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_alter_home_code_alter_room_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='wcmsPCfH0LOsy9egMqBu', max_length=100),
        ),
    ]
