# Generated by Django 5.1.7 on 2025-04-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_sensor_serial_number_alter_home_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='name',
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='TtwIWrodjs5eH4tgKzbs', max_length=100),
        ),
    ]
