# Generated by Django 5.1.7 on 2025-04-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_remove_measurement_name_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='wpMbOwuInvULeGBhUU9k', max_length=100),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='saved_at',
            field=models.DateTimeField(),
        ),
    ]
