# Generated by Django 5.1.7 on 2025-04-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_alter_home_code_alter_measurement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='4Xw07CEbXLmGwMxtvnFB', max_length=100),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
