# Generated by Django 5.1.7 on 2025-04-17 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_alter_home_code_alter_measurement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='PIJhDelulJWKPjOKhWQJ', max_length=100),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('isRead', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=1000)),
                ('time_triggered', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
