# Generated by Django 5.1.7 on 2025-04-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_alter_home_code_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='data_type',
            field=models.CharField(choices=[('LIGHT', 'światło'), ('HUMIDITY', 'wilgotność'), ('CONTINUOUS', 'inne ciągłe'), ('DISCRETE', 'inne dyskretne'), ('FUNCTIONAL', 'inne funkcyjne')], default='CONTINUOUS', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='U7CYRAck6PB4CNay9B8q', max_length=100),
        ),
    ]
