# Generated by Django 5.1.7 on 2025-04-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_device_owner_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('AUTO', 'automatycznie'), ('MANUAL', 'ręcznie')], default='AUTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='WxofXie4zPLBMjmMa7hL', max_length=100),
        ),
    ]
