# Generated by Django 5.1.7 on 2025-04-18 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_action_type_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='uAoXYpV2u1tRaJkYqgL8', max_length=100),
        ),
    ]
