# Generated by Django 5.1.7 on 2025-04-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0028_action_created_at_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='pVL14GwzHVnvP0J2au8q', max_length=100),
        ),
    ]
