# Generated by Django 5.1.7 on 2025-04-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='data_type',
            field=models.CharField(choices=[('LIGHT', 'światło'), ('HUMIDITY', 'wilgotność'), ('CONTINUOUS', 'inne ciągłe'), ('DISCRETE', 'inne dyskretne'), ('FUNCTIONAL', 'inne funkcyjne'), ('OTHER', 'inne/różne')], default='CONTINUOUS', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='data_type',
            field=models.CharField(choices=[('LIGHT', 'światło'), ('HUMIDITY', 'wilgotność'), ('CONTINUOUS', 'inne ciągłe'), ('DISCRETE', 'inne dyskretne'), ('FUNCTIONAL', 'inne funkcyjne'), ('OTHER', 'inne/różne')], default='CONTINUOUS', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='64DdRz4iTQvBRoxFmt5c', max_length=100),
        ),
    ]
