# Generated by Django 5.1.7 on 2025-04-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_sensor_data_type_alter_device_data_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='unit',
        ),
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='data_type',
            field=models.CharField(blank=True, choices=[('LIGHT', 'światło'), ('HUMIDITY', 'wilgotność'), ('CONTINUOUS', 'inne ciągłe'), ('DISCRETE', 'inne dyskretne'), ('FUNCTIONAL', 'inne funkcyjne'), ('OTHER', 'inne/różne')], default='CONTINUOUS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='y7yfB7nNzZZiXLt5Ed7a', max_length=100),
        ),
    ]
