# Generated by Django 5.1.7 on 2025-04-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0031_remove_device_unit_sensor_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='building_area',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='buildinq_type',
            field=models.CharField(choices=[('residual', 'mieszkalne'), ('public', 'publiczne'), ('industrial', 'przemysłowe'), ('commercial', 'komercyjne/handlowo-usługowe')], default='residual', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='home',
            name='year_of_construction',
            field=models.IntegerField(blank=True, default=2025, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='aFr7eRiit5qxOtbXrmNr', max_length=100),
        ),
    ]
