# Generated by Django 5.1.7 on 2025-04-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0032_home_building_area_home_buildinq_type_home_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='Jdonfy9dYfVgPRoDOcyx', max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='year_of_construction',
            field=models.DateField(blank=True, default=2025, null=True),
        ),
    ]
