# Generated by Django 5.1.7 on 2025-04-19 01:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0033_alter_home_code_alter_home_year_of_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='h9iHkwhZ7NdkL7oYBS02', max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='year_of_construction',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
