# Generated by Django 5.1.7 on 2025-04-19 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_alter_home_code_alter_home_year_of_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='bX7ZRwbWupE4pzSsn5va', max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='home',
            name='regards',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='year_of_construction',
            field=models.IntegerField(blank=True, default=2025, null=True),
        ),
    ]
