# Generated by Django 5.1.7 on 2025-05-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0035_alter_home_code_alter_home_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='MAwhFphKLOW1Bv30pDLl', max_length=100),
        ),
    ]
