# Generated by Django 5.2.2 on 2025-07-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0036_home_isactive_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('1', 'krytyczny'), ('2', 'ostrzeżenie'), ('3', 'informacja'), ('4', 'inne')], default='3', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='s0YceNUEiebQZZhqDvC3', max_length=100),
        ),
    ]
