# Generated by Django 5.2.2 on 2025-07-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0037_action_status_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='KpwxrNcnJpMgWVNXXSHU', max_length=100),
        ),
    ]
