# Generated by Django 5.2.2 on 2025-07-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0038_action_priority_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='lng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='hY5BtNFZcgM6FybmmY1w', max_length=100),
        ),
    ]
