# Generated by Django 5.2.2 on 2025-07-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0039_home_lat_home_lng_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='SkcwrhmA1ZpUbiSzcbET', max_length=100),
        ),
    ]
