# Generated by Django 5.2.2 on 2025-07-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0040_device_isactive_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='x3sL4DClVeK86Lq9zUVJ', max_length=100),
        ),
    ]
