# Generated by Django 5.2.2 on 2025-07-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0041_measurement_name_alter_home_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='name',
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='XZL5X5LJs8rYpGzQK2yv', max_length=100),
        ),
    ]
