# Generated by Django 5.2.2 on 2025-07-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0042_remove_measurement_name_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='visibleName',
            field=models.CharField(default=models.CharField(max_length=200), max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='rKc8ahLkoSqOU5otDHOQ', max_length=100),
        ),
    ]
