# Generated by Django 5.2.2 on 2025-07-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0043_sensor_visiblename_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='color',
            field=models.CharField(default='#42adf5', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='AZTb05mbwfc4c3dD4rX2', max_length=100),
        ),
    ]
