# Generated by Django 5.2.2 on 2025-07-14 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0044_device_color_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.floor'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='mainApp.home'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='8GsnTfveF0d1lcZMzsBW', max_length=100),
        ),
    ]
