# Generated by Django 5.2.2 on 2025-07-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0045_device_floor_device_location_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='NitI5gZIQQvkNpkxAOxS', max_length=100),
        ),
    ]
