# Generated by Django 5.2.2 on 2025-07-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0046_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='2b3uIiXwKPITH9HowpoT', max_length=100),
        ),
    ]
