# Generated by Django 5.2.2 on 2025-07-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0047_device_isfavorite_home_isfavorite_room_isfavorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='isConfigured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='7FipQOU5Ul5xXrWr8HDg', max_length=100),
        ),
    ]
