# Generated by Django 5.2.2 on 2025-07-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0048_device_isconfigured_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='topic',
            field=models.CharField(default='<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>_<django.db.models.fields.related.ForeignKey>_<django.db.models.fields.AutoField>', max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='JG4njxOVKX72cwnQMmXL', max_length=100),
        ),
    ]
