# Generated by Django 5.2.2 on 2025-07-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0049_alter_device_topic_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='83pLsZEQ9l4Mw5X9KBm2', max_length=100),
        ),
    ]
