# Generated by Django 5.2.2 on 2025-07-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0050_alter_device_topic_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='9Hfjklt7fkNnkkLvdVgR', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='visibleName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
