# Generated by Django 5.2.2 on 2025-07-18 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0051_alter_home_code_alter_sensor_visiblename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='EWOZbrkfkJIfi3EVfBhS', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='data_type',
            field=models.CharField(choices=[('LIGHT', 'światło'), ('HUMIDITY', 'wilgotność'), ('ENERGY', 'zużycie energii'), ('TEMPERATURE', 'temperatura'), ('CONTINUOUS', 'ciągłe'), ('DISCRETE', 'dyskretne'), ('OTHER', 'inne/różne')], default='CONTINUOUS', max_length=20),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('value_low', models.CharField(blank=True, max_length=10, null=True)),
                ('value_high', models.CharField(blank=True, max_length=10, null=True)),
                ('isRecurrent', models.BooleanField(default=False)),
                ('recurrentTime', models.CharField(blank=True, choices=[('1', 'godzinowo'), ('2', 'dziennie'), ('3', 'tygodniowo'), ('4', 'miesięcznie'), ('5', 'rocznie')], max_length=20, null=True)),
                ('floors', models.ManyToManyField(blank=True, to='mainApp.floor')),
                ('locations', models.ManyToManyField(blank=True, to='mainApp.home')),
                ('rooms', models.ManyToManyField(blank=True, to='mainApp.room')),
            ],
        ),
    ]
