# Generated by Django 5.2.2 on 2025-07-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0052_alter_home_code_alter_sensor_data_type_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='floor',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='isSamePlaceAsDevice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='isSameTypeAsDevice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='data_type',
            field=models.CharField(blank=True, choices=[('LIGHT', 'światło'), ('HUMIDITY', 'wilgotność'), ('ENERGY', 'zużycie energii'), ('TEMPERATURE', 'temperatura'), ('CONTINUOUS', 'ciągłe'), ('DISCRETE', 'dyskretne'), ('OTHER', 'inne/różne')], default='CONTINUOUS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='tgKXlR6f4yLCCqyQVUqM', max_length=100),
        ),
    ]
