# Generated by Django 5.2.2 on 2025-07-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0053_device_isarchived_floor_isarchived_home_isarchived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='v2tH7Y6WSAAAQqpVEZ9G', max_length=100),
        ),
    ]
