# Generated by Django 5.2.2 on 2025-07-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0054_measurement_warning_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='iWb7VYl8GQRR9Z7iM8NN', max_length=100),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='warning',
            field=models.CharField(choices=[('LOW', 'niskie'), ('MEDIUM', 'średnie'), ('HIGH', 'wysokie'), ('NORMAL', 'brak')], default='NORMAL', max_length=200),
        ),
    ]
