# Generated by Django 5.2.2 on 2025-07-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0055_alter_home_code_alter_measurement_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='isAcknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('LOW', 'niskie'), ('MEDIUM', 'średnie'), ('HIGH', 'wysokie'), ('NORMAL', 'brak')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='XCs4Ypo9SpSd3TuBBjkj', max_length=100),
        ),
    ]
