# Generated by Django 5.2.2 on 2025-07-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0056_action_isacknowledged_alter_action_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='sensors',
            field=models.ManyToManyField(blank=True, to='mainApp.sensor'),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='s7n3GPZaevx0Mk2X6xTZ', max_length=100),
        ),
    ]
