# Generated by Django 5.2.2 on 2025-07-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0057_rule_sensors_alter_home_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='isActive',
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='3NMD3A80SvAFH187O1XB', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='data_type',
            field=models.CharField(choices=[('LIGHT', 'światło'), ('HUMIDITY', 'wilgotność'), ('ENERGY', 'zużycie energii'), ('TEMPERATURE', 'temperatura'), ('CONTINUOUS', 'ciągłe'), ('DISCRETE', 'dyskretne'), ('WORKER', 'sterowanie'), ('OTHER', 'inne/różne')], default='CONTINUOUS', max_length=20),
        ),
    ]
