# Generated by Django 5.2.2 on 2025-07-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0058_remove_home_isactive_alter_home_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='G4MBEU1R1EC4AOwjlLsW', max_length=100),
        ),
    ]
