# Generated by Django 5.2.2 on 2025-07-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0059_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='devices',
            field=models.ManyToManyField(blank=True, to='mainApp.device'),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='e3i0gvJGXpTlZidBIwZI', max_length=100),
        ),
    ]
