# Generated by Django 5.2.2 on 2025-07-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0060_rule_devices_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='type',
            field=models.CharField(choices=[('ON/OFF', 'włącz/wyłącz'), ('LIMIT', 'limity'), ('SET', 'ustawienie')], default='LIMIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='t1qCxiW2ac0T6i1nhGxY', max_length=100),
        ),
    ]
