# Generated by Django 5.2.2 on 2025-07-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0061_rule_type_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='f0jSLKH6myIPQLovfJg9', max_length=100),
        ),
    ]
