# Generated by Django 5.2.2 on 2025-07-21 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0062_rule_isactive_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='3HlcJ7DpIkz8rAcUxa4X', max_length=100),
        ),
    ]
