# Generated by Django 5.2.2 on 2025-07-24 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0063_rule_owner_alter_home_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.rule'),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='f9Od2T8EUZkcQ1hygbkX', max_length=100),
        ),
    ]
