# Generated by Django 5.2.2 on 2025-07-25 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0064_action_rule_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.device'),
        ),
        migrations.AlterField(
            model_name='action',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainApp.measurement'),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='QqXBzDvPfn3osvrNBFTM', max_length=100),
        ),
    ]
