# Generated by Django 5.2.2 on 2025-07-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0065_alter_action_device_alter_action_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='uibyuXW7jTuqiI2qtiZE', max_length=100),
        ),
    ]
