# Generated by Django 5.2.2 on 2025-07-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0066_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='Gfdgnd3uOfidKU6VCGAn', max_length=100),
        ),
    ]
