# Generated by Django 5.2.2 on 2025-07-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0067_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='6j9F8lHEu5lDdJc6gdy9', max_length=100),
        ),
    ]
