# Generated by Django 5.2.2 on 2025-07-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0068_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='tk5xnnFQr6EfYJuXpeSM', max_length=100),
        ),
    ]
