# Generated by Django 5.2.2 on 2025-07-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0069_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='07voQDKW6gDZIIgGqLYz', max_length=100),
        ),
    ]
