# Generated by Django 5.2.2 on 2025-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0070_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default='yafH4Je8j6Qni2QdG9XO', max_length=100),
        ),
    ]
