# Generated by Django 5.2.2 on 2025-07-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0071_alter_home_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='code',
        ),
    ]
